version: '2'

services:
  frontend:
    build: frontend
    ports:
      - "4200:4200"
    links:
      - backend
    image: registry.gitlab.com/delftschestudentenbond/projectbetrayal/frontend
  
  backend:
    build: backend
    ports:
      - "3000:3000"
    links:
      - database
    image: registry.gitlab.com/delftschestudentenbond/projectbetrayal/backend

  database:
    image: mongo
    ports:
      - "27017:27017"