version: '2'

services:
  frontend:
    build: frontend
    ports:
      - "4200:4200"
    links:
      - backend
    depends_on:
      - backend
    image: projectbetrayal/frontend

  backend:
    build: backend
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database
    environment:
      MONGO_HOST: database
    image: projectbetrayal/backend

  database:
    image: mongo
    ports:
      - "27017:27017"